trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'terraform/*'

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    displayName: 'build all'
    workspace:
      clean: all
    steps:
      - template: 'Terraform-CI.yml'
