jobs:
- job: checkArtifact
  displayName: 'Check Pipeline Artifact'
  steps:
    - task: PowerShell@2
      displayName: 'Check Pipeline Artifact'
      inputs:
        targetType: 'inline'
        script: |
          $artifactExists = Test-Path -Path "$(Pipeline.Workspace)/terraform"
          if ($artifactExists) {
              Write-Host "Artifact exists."
              Write-Host "##vso[task.setvariable variable=ArtifactExists]True"
          } else {
              Write-Host "Artifact does not exist."
              Write-Host "##vso[task.setvariable variable=ArtifactExists]False"
          }
