resources:
  pipelines:
  - pipeline: terraform-iac
    source: terraform-iac

variables:
- group: terraform
- name: $rgterraform
  value: '$(rgterraform)'
- name: $scterraform
  value: '$(scterraform)'
- name: $projectname
  value: $(projectname)
- name: $environment
  value: $(environment)

jobs:
- job: Job_1
  displayName: Web-set-variable
  pool:
    vmImage: windows-latest
  steps:
    - task: AzureCLI@2
      displayName: 'Get acr variable'
      inputs:
        connectedServiceNameARM: 'sc-terraform'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: >-
          $acrname = "acr"+$(projectname)+$(environment)

          Write-Host "##vso[task.setvariable variable=acrname]$acrname"

          $username=$(az acr credential show --name $acrname --resource-group $(rgterraform) --query "username" --output tsv)

          $password=$(az acr credential show --name $acrname --resource-group $(rgterraform) --query "passwords[0].value" --output tsv)

          $loginserver = $username + ".azurecr.io"

          Write-Host $username $password $loginserver

          Write-Host "##vso[task.setvariable variable=username]$username"

          Write-Host "##vso[task.setvariable variable=password]$password"

          Write-Host "##vso[task.setvariable variable=loginserver]$loginserver"