resources:
  pipelines:
  - pipeline: terraform-iac
    source: terraform-iac

variables:
- group: terraform
- name: $rgterraform
  value: '$(rgterraform)'
- name: $scterraform
  value: '$(scterraform)'
- name: $projectname
  value: $(projectname)
- name: $environment
  value: $(environment)

jobs:
- job: Job_1
  displayName: Web-set-variable
  pool:
    vmImage: windows-latest
  steps:
    - task: AzureCLI@2
      displayName: 'Get acr variable'
      inputs:
        connectedServiceNameARM: 'sc-terraform'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: >-
          az acr list --output table --resource-group rg-optimastruct-prod

          