trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: build
  displayName: 'API and Web App Build'
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download yml config Artifact
      continueOnError: true
      inputs:
        source: specific
        project: '$(System.TeamProject)'
        pipeline: 'web-set-var'
        preferTriggeringPipeline: true
        artifact: config
        path: $(Pipeline.Workspace)/config
        allowPartiallySucceededBuilds: true
    - task: DownloadPipelineArtifact@2
      displayName: Download website Artifact
      continueOnError: true
      inputs:
        source: specific
        project: '$(System.TeamProject)'
        pipeline: 'web-set-var'
        preferTriggeringPipeline: true
        artifact: web
        path: $(Pipeline.Workspace)/web
        allowPartiallySucceededBuilds: true
    - task: PowerShell@2
      inputs:
        filePath: '$(Pipeline.Workspace)/config/powershell.ps1'
    - template: 'web-api-CICD.yml'
    - template: 'web-app-CICD.yml'
