trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'web/api/*'
      - 'web/app/*'

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: build
  displayName: 'API and Web App Build'
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - task: PowerShell@2
      displayName: 'List Folders and Files'
      inputs:
        targetType: 'inline'
        script: |
          $rootPath = "$(System.DefaultWorkingDirectory)"  # Replace with the path of the root folder

          function Get-FolderContents {
              param([string]$path)

              Get-ChildItem -Path $path -Recurse | ForEach-Object {
                  $item = $_
                  $type = $_.PSIsContainer ? "Folder" : "File"
                  $relativePath = Convert-Path -Relative $_.FullName -ErrorAction SilentlyContinue
                  Write-Output "${type}: ${relativePath}"
              }
          }

          Get-FolderContents -path $rootPath

    - task: DownloadPipelineArtifact@2
      displayName: Download yml config Artifact
      continueOnError: true
      inputs:
        source: specific
        project: 'OptimaStruct'
        pipeline: 'terraform-iac'
        preferTriggeringPipeline: true
        artifact: pipelines
        path: $(Pipeline.Workspace)/pipelines
        allowPartiallySucceededBuilds: true
    - task: CopyFiles@2
      displayName: 'Copy Files to: pipelines'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/pipelines'
        TargetFolder: pipelines
    - task: DownloadPipelineArtifact@2
      displayName: Download web config Artifact
      continueOnError: true
      inputs:
        source: specific
        project: 'OptimaStruct'
        pipeline: 'terraform-iac'
        preferTriggeringPipeline: true
        artifact: web
        path: $(Pipeline.Workspace)/web
        allowPartiallySucceededBuilds: true
    - task: CopyFiles@2
      displayName: 'Copy Files to: web'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/web'
        TargetFolder: web
    - template: 'web-api-CICD.yml'
    - template: 'web-app-CICD.yml'
