trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'web/api/*'
      - 'web/app/*'

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: build
  displayName: 'API and Web App Build'
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - template: 'web-api-CICD.yml'
    - template: 'web-app-CICD.yml'
